[package]
name = "participant_downloader"
version = "0.1.0"
authors = ["Tor Hovland"]

[dependencies]
pbp_shared = { path = "../pbp_shared" }
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.33"
