[package]
name = "participant-downloader"
version = "0.1.0"
authors = ["Tor Hovland"]

[dependencies]
failure = "0.1.3"
reqwest = "0.9.4"
scraper = "0.8.1"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.33"
